### ISSUE TITLE
mul got incompatible shapes 

### ISSUE THREAD

**Issue by c03n424** [sarafridov/plenoxels#2]
Exception has occurred: TypeError
**mul got incompatible shapes for broadcasting: (800, 800, 1, 1536), (800, 1, 800, 3)**.
  File "/plenoxels/plenoptimize.py", line 479, in <module>
    main()
  File "/plenoxels/plenoptimize.py", line 419, in main
    mse, data_grad = jax.value_and_grad(lambda grid: get_loss((indices, grid), c2w, gt, H, W, focal, FLAGS.resolution, radius, FLAGS.harmonic_degree, FLAGS.jitter, FLAGS.uniform, subkeys, sh_dim, occupancy_penalty, FLAGS.interpolation, FLAGS.nv))(data)
  File "/plenoxels/plenoptimize.py", line 419, in <lambda>
    mse, data_grad = jax.value_and_grad(lambda grid: get_loss((indices, grid), c2w, gt, H, W, focal, FLAGS.resolution, radius, FLAGS.harmonic_degree, FLAGS.jitter, FLAGS.uniform, subkeys, sh_dim, occupancy_penalty, FLAGS.interpolation, FLAGS.nv))(data)
  File "/plenoxels/plenoptimize.py", line 285, in get_loss
    rgb, disp, acc, weights, voxel_ids = plenoxel.render_rays(data_dict, rays, resolution, key, radius, harmonic_degree, jitter, uniform, interpolation, nv)
  File "/plenoxels/plenoxel.py", line 490, in render_rays
    pts = rays_o[:, jnp.newaxis, :] + intersections[:, :, jnp.newaxis] * rays_d[:, jnp.newaxis, :]  # [n_rays, n_intersections, 3]

**Comment by sarafridov** [comment]
Sorry about this...the issue was because some of the code is only written to work with ray batches (rather than full images) during training. I changed the defaults to use ray batches instead of the full image, and the error should be resolved.

**Comment by c03n424** [comment]
It works.
