### ISSUE TITLE
About the negative density in voxel

### ISSUE THREAD

**Issue by Fangkang515** [sarafridov/plenoxels#6]
Thanks for your astonishing work. 

I notice that some voxels have negative density or zero density. I was wondering how the density is defined if it's negative. 
According to Formulas 1 and 2 in the plenoxel paper, if density is negative, the result of RGB may be unreasonable. However, I did some experiments to clip the density in the trained model，and the PSNR decreased. 

I didn't find a value domain constraint on density in the code. Maybe I missed something. So I hope to get your opinion.

Thanks!

**Comment by sarafridov** [comment]
During rendering, negative densities are clipped to zero with a ReLU: https://github.com/sarafridov/plenoxels/blob/main/plenoxel.py#L31

**Comment by Fangkang515** [comment]
Thank you very much for your substantial reply. And I have another question about this. Since the negative densities are clipped to zero with a ReLU during rendering, why not add a nonnegative constraint on density in the optimization stage. That is, ensure that the densities stored on the voxel is positive.  
Have you done any related experiments? How's the effect?  
Hope to get your opinion. Thanks!

**Comment by sarafridov** [comment]
I don't remember if we tried this or not, but I wouldn't expect it to change anything. In some sense this happens anyway during the pruning phase, because empty voxels are deleted (replaced with all zeros).
